#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2023 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
  automatic_update = true
  buffer_index_type = 4
  code_runner_focus = true
  colorscheme = 'gruvbox'
  colorscheme_bg = 'dark'
  enable_cursorcolumn = true
  enable_cursorline = true
  enable_googlesuggest = true
  enable_guicolors = true
  enable_statusline_mode = true
  enable_statusline_tag = true
  enable_tabline_filetype_icon = true
  guifont = 'DejaVuSansMono NFM:h10'
  project_rooter_outermost = false
  statusline_iseparator = 'arrow'
  statusline_separator = 'arrow'

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = 'complete'
  auto_completion_tab_key_behavior = 'smart'

[[layers]]
  name = 'telescope'

[[layers]]
  name = 'format'

[[layers]]
  name = 'checkers'

[[layers]]
  name = 'ctrlspace'

[[layers]]
  name = 'git'

[[layers]]
  name = 'github'

[[layers]]
  name = 'gtags'

[[layers]]
  name = 'lang#asciidoc'

[[layers]]
  name = 'lang#assembly'

[[layers]]
  name = 'lang#batch'

[[layers]]
  name = 'lang#c'
  enable_clang_syntax_highlight = true

[[layers]]
  name = 'lang#clojure'

[[layers]]
  name = 'lang#cmake'

[[layers]]
  name = 'lang#crystal'

[[layers]]
  name = 'lang#csharp'

[[layers]]
  name = 'lang#d'

[[layers]]
  name = 'lang#dart'

[[layers]]
  name = 'lang#dockerfile'

[[layers]]
  name = 'lang#e'

[[layers]]
  name = 'lang#eiffel'

[[layers]]
  name = 'lang#elixir'

[[layers]]
  name = 'lang#elm'

[[layers]]
  name = 'lang#erlang'

[[layers]]
  name = 'lang#factor'

[[layers]]
  name = 'lang#fortran'

[[layers]]
  name = 'lang#fsharp'

[[layers]]
  name = 'lang#go'

[[layers]]
  name = 'lang#graphql'

[[layers]]
  name = 'lang#haskell'

[[layers]]
  name = 'lang#haxe'

[[layers]]
  name = 'lang#html'

[[layers]]
  name = 'lang#idris'

[[layers]]
  name = 'lang#io'

[[layers]]
  name = 'lang#ipynp'

[[layers]]
  name = 'lang#java'

[[layers]]
  name = 'lang#javascript'

[[layers]]
  name = 'lang#json'

[[layers]]
  name = 'lang#jsonnet'

[[layers]]
  name = 'lang#julia'

[[layers]]
  name = 'lang#kotlin'

[[layers]]
  name = 'lang#lisp'

[[layers]]
  name = 'lang#livescript'

[[layers]]
  name = 'lang#lua'

[[layers]]
  name = 'lang#markdown'

[[layers]]
  name = 'lang#nim'

[[layers]]
  name = 'lang#nix'

[[layers]]
  name = 'lang#ocaml'

[[layers]]
  name = 'lang#org'

[[layers]]
  name = 'lang#packt'

[[layers]]
  name = 'lang#pascal'

[[layers]]
  name = 'lang#perl'

[[layers]]
  name = 'lang#php'

[[layers]]
  name = 'lang#plantuml'

[[layers]]
  name = 'lang#pony'

[[layers]]
  name = 'lang#powershell'

[[layers]]
  name = 'lang#processing'

[[layers]]
  name = 'lang#prolog'

[[layers]]
  name = 'lang#python'

[[layers]]
  name = 'lang#r'

[[layers]]
  name = 'lang#racket'

[[layers]]
  name = 'lang#reason'

[[layers]]
  name = 'lang#red'

[[layers]]
  name = 'lang#rescript'

[[layers]]
  name = 'lang#ring'

[[layers]]
  name = 'lang#rst'

[[layers]]
  name = 'lang#ruby'

[[layers]]
  name = 'lang#rust'

[[layers]]
  name = 'lang#scheme'

[[layers]]
  name = 'lang#swift'

[[layers]]
  name = 'lang#teal'

[[layers]]
  name = 'lang#toml'

[[layers]]
  name = 'lang#typescript'

[[layers]]
  name = 'lang#v'

[[layers]]
  name = 'lang#vim'

[[layers]]
  name = 'lang#vue'

[[layers]]
  name = 'lang#xml'

[[layers]]
  name = 'lang#zig'

[[layers]]
  name = 'lsp'
  filetypes = [ 'c', 'cpp', 'go', 'java', 'javascript', 'javascriptreact', 'lua', 'nim', 'python', 'rust', 'typescript']
  [layers.override_cmd]
    rust = ['rls']  

[[layers]]
  name = 'mail'

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = 'ssh'

[[layers]]
  name = 'sudo'

[[layers]]
  name = 'test'

[[layers]]
  name = 'treesitter'

[[layers]]
  name = 'tools'

[[layers]]
  name = 'tools#dash'

[[layers]]
  name = 'tools#zeal'

[[layers]]
  name = 'tools#zeal'

[[layers]]
  name = 'VersionControl'

[[layers]]
  name = 'zettelkasten'

