#!/bin/bash

failed_items=""
function install_package() {
echo EXECUTING: brew install $1 $2
brew install $1 $2
[ $? -ne 0 ] && $failed_items="$failed_items $1"  # package failed to install.
}
brew tap caskroom/cask
brew tap dart-lang/dart
brew tap homebrew/python
brew tap homebrew/science
brew tap homebrew/versions
brew tap staticfloat/julia
install_package activemq ''
install_package activemq-cpp ''
install_package akka ''
install_package android-ndk ''
install_package android-sdk ''
install_package ant ''
install_package apache-forrest ''
install_package apache-opennlp ''
install_package apache-spark ''
install_package apachetop ''
install_package arangodb ''
install_package armadillo '  --c++11'
install_package arpack ''
install_package arpack-julia ''
install_package atk ''
install_package autoconf ''
install_package automake ''
install_package avro-c ''
install_package avro-cpp ''
install_package avro-tools ''
install_package bazaar ''
install_package bison ''
install_package boost '  --c++11'
install_package c-ares ''
install_package cabal-install ''
install_package cairo ''
install_package cassandra ''
install_package checkstyle ''
install_package clisp ''
install_package cloog ''
install_package cloog018-julia ''
install_package cmake ''
install_package couchdb ''
install_package cowsay ''
install_package cppunit ''
install_package cscope ''
install_package ctags ''
install_package d-bus ''
install_package dart ''
install_package dartium ''
install_package dmd ''
install_package ecj ''
install_package eigen ''
install_package elixir ''
install_package emacs '  --cocoa  --with-d-bus  --with-mailutils  --with-imagemagick  --with-gnutls  --with-x11  --with-librsvg'
install_package epstool ''
install_package erlang '  --with-fop'
install_package fftw ''
install_package flac ''
install_package flex ''
install_package fltk ''
install_package fontconfig ''
install_package fop ''
install_package fortune ''
install_package freetype ''
install_package gawk ''
install_package gcc '  --with-all-languages  --with-nls'
install_package gd ''
install_package gdbm ''
install_package gdk-pixbuf ''
install_package geoip ''
install_package gettext ''
install_package ghc ''
install_package ghostscript ''
install_package git ''
install_package gl2ps ''
install_package glib ''
install_package glpk ''
install_package gmp ''
install_package gmp4-julia ''
install_package gnu-prolog ''
install_package gnu-sed ''
install_package gnuplot '  --latex  --with-x11'
install_package gnutls ''
install_package go ''
install_package gobject-introspection ''
install_package gradle ''
install_package graphicsmagick ''
install_package groovy '  --invokedynamic'
install_package gsasl ''
install_package gtk+ ''
install_package gwt ''
install_package hadoop ''
install_package harfbuzz ''
install_package hbase ''
install_package hdf5 ''
install_package hive ''
install_package icu4c ''
install_package ilmbase ''
install_package imagemagick ''
install_package io '  --with-python'
install_package isl ''
install_package isl011-julia ''
install_package jbig2dec ''
install_package jmeter '  --with-plugins'
install_package jpeg ''
install_package jsoncpp ''
install_package julia ''
install_package leiningen ''
install_package libcroco ''
install_package libevent ''
install_package libffi ''
install_package libgcrypt ''
install_package libgpg-error ''
install_package libmpc ''
install_package libogg ''
install_package libpng ''
install_package librsvg ''
install_package libsigsegv ''
install_package libsndfile ''
install_package libtasn1 ''
install_package libtiff ''
install_package libtool ''
install_package libvorbis ''
install_package libxml2 ''
install_package libyaml ''
install_package little-cms2 ''
install_package llvm33-julia ''
install_package lua ''
install_package luajit ''
install_package macvim '  --override-system-vim  --with-lua  --with-luajit  --with-python3'
install_package makedepend ''
install_package mahout ''
install_package mailutils ''
install_package maven ''
install_package mercurial ''
install_package mit-scheme ''
install_package mlpack '  --c++11'
install_package mongodb ''
install_package mpfr ''
install_package mysql ''
install_package neo4j ''
install_package nettle ''
install_package newlisp ''
install_package node ''
install_package nspr ''
install_package ntfs-3g ''
install_package objective-caml '  --with-x11'
install_package openblas ''
install_package openblas-julia ''
install_package openexr ''
install_package openssl ''
install_package ossp-uuid ''
install_package pango ''
install_package pcre ''
install_package pig ''
install_package pixman ''
install_package pkg-config ''
install_package plotutils ''
install_package plt-racket ''
install_package popt ''
install_package portmidi ''
install_package postgresql '  --with-python'
install_package pstoedit ''
install_package pypy ''
install_package pypy3 ''
install_package pyqt5 '  --enable-debug'
install_package python ''
install_package python3 ''
install_package qhull ''
install_package qrupdate ''
install_package qt5 '  --developer  --with-d-bus  --with-mysql'
install_package quantlib '  --c++11'
install_package r '  --with-openblas'
install_package rabbitmq ''
install_package rabbitmq-c ''
install_package readline ''
install_package redis ''
install_package riak ''
install_package ruby ''
install_package rust ''
install_package sbt ''
install_package scala ''
install_package scons ''
install_package sdl ''
install_package sdl_image ''
install_package sdl_mixer ''
install_package sdl_ttf ''
install_package sip '  --with-python3'
install_package spidermonkey ''
install_package sqlite ''
install_package suite-sparse ''
install_package suite-sparse-julia ''
install_package szip ''
install_package tbb ''
install_package texinfo ''
install_package thrift '  --with-erlang  --with-haskell  --with-java  --with-python'
install_package tmux ''
install_package unixodbc ''
install_package veclibfort ''
install_package webp ''
install_package wireshark '  --with-lua'
install_package wxmac ''
install_package xctool ''
install_package xz ''
install_package yajl ''
install_package zeromq ''
install_package zookeeper '  --with-python'
install_package zsh ''
install_package zsh-completions ''
install_package zsh-history-substring-search ''
install_package zsh-lovers ''
install_package zsh-syntax-highlighting ''
install_package yaws ''
[ ! -z $failed_items ] && echo The following items were failed to install: && echo $failed_items
